const titles = [
  { title: "Acemi", point: 0, condition: "" },
  { title: "Yeni Başlayan", point: 0, condition: "" },
  { title: "Deneyimli", point: 0, condition: "" },
  { title: "Uzman", point: 0, condition: "" },
  { title: "Profesyonel", point: 0, condition: "" },
  { title: "Deneme Yapan", point: 0, condition: "" },
  { title: "Yetenekli", point: 0, condition: "" },
  { title: "Becerikli", point: 0, condition: "" },
  { title: "İleri Seviye", point: 0, condition: "" },
  { title: "Gelişmekte Olan", point: 0, condition: "" },
  { title: "Hünerli", point: 0, condition: "" },
  { title: "Zeki", point: 0, condition: "" },
  { title: "Çalışkan", point: 0, condition: "" },
  { title: "Performansı Yüksek", point: 0, condition: "" },
  { title: "Gözde", point: 0, condition: "" },
  { title: "Lider", point: 0, condition: "" },
  { title: "Vizyoner", point: 0, condition: "" },
  { title: "Yaratıcı", point: 0, condition: "" },
  { title: "Hızlı", point: 0, condition: "" },
  { title: "Güçlü", point: 0, condition: "" },
  { title: "Dikkatli", point: 0, condition: "" },
  { title: "Pratik", point: 0, condition: "" },
  { title: "Hızlı Düşünen", point: 0, condition: "" },
  { title: "Problem Çözücü", point: 0, condition: "" },
  { title: "Kararlı", point: 0, condition: "" },
  { title: "Azimli", point: 0, condition: "" },
  { title: "Esnek", point: 0, condition: "" },
  { title: "Dinamik", point: 0, condition: "" },
  { title: "Verimli", point: 0, condition: "" },
  { title: "Etkili", point: 0, condition: "" },
  { title: "Sonuç Odaklı", point: 0, condition: "" },
  { title: "Güvenilir", point: 0, condition: "" },
  { title: "Sorumluluk Sahibi", point: 0, condition: "" },
  { title: "Organize", point: 0, condition: "" },
  { title: "Planlayıcı", point: 0, condition: "" },
  { title: "Stratejik Düşünen", point: 0, condition: "" },
  { title: "İletişimci", point: 0, condition: "" },
  { title: "İşbirlikçi", point: 0, condition: "" },
  { title: "Takım Oyuncusu", point: 0, condition: "" },
  { title: "Liderlik Yatkını", point: 0, condition: "" },
  { title: "Motive Edici", point: 0, condition: "" },
  { title: "Enerjik", point: 0, condition: "" },
  { title: "İyi Dinleyen", point: 0, condition: "" },
  { title: "Empatik", point: 0, condition: "" },
  { title: "Güler Yüzlü", point: 0, condition: "" },
  { title: "Olumlu", point: 0, condition: "" },
  { title: "Pozitif", point: 0, condition: "" },
  { title: "İyi İletişim Kurabilen", point: 0, condition: "" },
  { title: "İş Ahlakına Sahip", point: 0, condition: "" },
  { title: "Disiplinli", point: 0, condition: "" },
  { title: "Detay Odaklı", point: 0, condition: "" },
  { title: "Hızlı Öğrenen", point: 0, condition: "" },
  { title: "Adaptasyon Yeteneği Yüksek", point: 0, condition: "" },
  { title: "Esnek Çalışma Saatlerine Uyumlu", point: 0, condition: "" },
  { title: "Stres Yönetimi Becerisi Yüksek", point: 0, condition: "" },
  { title: "Çözüm Odaklı Düşünen", point: 0, condition: "" },
  { title: "Yenilikçi", point: 0, condition: "" },
  { title: "Geleceği Gören", point: 0, condition: "" },
  { title: "Trendleri Takip Eden", point: 0, condition: "" },
  { title: "Değişime Açık", point: 0, condition: "" },
  { title: "Gelecek Odaklı", point: 0, condition: "" },
  { title: "Teknolojiyi Kullanan", point: 0, condition: "" },
  { title: "Veri Odaklı", point: 0, condition: "" },
  { title: "Analitik Düşünen", point: 0, condition: "" },
  { title: "Risk Alabilen", point: 0, condition: "" },
  { title: "Girişimci", point: 0, condition: "" },
  { title: "Yenilikleri Benimseyen", point: 0, condition: "" },
  { title: "Fırsatları Değerlendiren", point: 0, condition: "" },
  { title: "Özgün Fikirlere Sahip", point: 0, condition: "" },
  { title: "Yaratıcı Çözümler Sunan", point: 0, condition: "" },
  { title: "İnovatif", point: 0, condition: "" },
  { title: "Yeniliklere Açık", point: 0, condition: "" },
  { title: "Yenilikleri Destekleyen", point: 0, condition: "" },
  { title: "Geleceği Şekillendiren", point: 0, condition: "" },
  { title: "Geleceği Yönlendiren", point: 0, condition: "" },
  { title: "Yenilikleri Yönlendiren", point: 0, condition: "" },
  { title: "Yeniliklere İlham Veren", point: 0, condition: "" },
  { title: "Geleceğe Yön Veren", point: 0, condition: "" },
  { title: "Öncü", point: 0, condition: "" },
  { title: "Liderlik Edebilen", point: 0, condition: "" },
  { title: "Gelişimi Yönlendiren", point: 0, condition: "" },
  { title: "Topluma Katkıda Bulunan", point: 0, condition: "" },
  { title: "Değişimi Yönlendiren", point: 0, condition: "" },
  { title: "Toplumsal Fark Yaratan", point: 0, condition: "" },
  { title: "Sosyal Sorumluluk Alan", point: 0, condition: "" },
  { title: "Sosyal Farkındalık Oluşturan", point: 0, condition: "" },
  { title: "Sürdürülebilirliği Destekleyen", point: 0, condition: "" },
  { title: "Doğaya Saygılı", point: 0, condition: "" },
  { title: "Çevre Dostu", point: 0, condition: "" },
  { title: "Doğal Kaynakları Koruyan", point: 0, condition: "" },
  { title: "Yeşil Düşünen", point: 0, condition: "" },
  { title: "Doğa Dostu", point: 0, condition: "" },
  { title: "Sosyal Adaleti Savunan", point: 0, condition: "" },
  { title: "Eşitliği Destekleyen", point: 0, condition: "" },
  { title: "Adaletli", point: 0, condition: "" },
  { title: "Adil Davranan", point: 0, condition: "" },
  { title: "Hakça Davranan", point: 0, condition: "" },
  { title: "Hakkaniyetli", point: 0, condition: "" },
  { title: "Adaletli Yaklaşan", point: 0, condition: "" },
  { title: "Kurallara Uyan", point: 0, condition: "" },
  { title: "Etik", point: 0, condition: "" },
  { title: "Saygılı", point: 0, condition: "" },
  { title: "Dürüst", point: 0, condition: "" },
  { title: "Güvenilir", point: 0, condition: "" },
  { title: "Gizliliğe Önem Veren", point: 0, condition: "" },
  { title: "Kişisel Verilere Saygılı", point: 0, condition: "" },
  { title: "Saygın", point: 0, condition: "" },
  { title: "Başarılı", point: 0, condition: "" },
  { title: "Başarı Odaklı", point: 0, condition: "" },
  { title: "Hedef Odaklı", point: 0, condition: "" },
  { title: "Başarıya İnanan", point: 0, condition: "" },
  { title: "Hedefe Ulaşmayı Hedefleyen", point: 0, condition: "" },
  { title: "Sonuç Odaklı", point: 0, condition: "" },
  { title: "Başarıyı Tutan", point: 0, condition: "" },
  { title: "Kazanan", point: 0, condition: "" },
  { title: "Rekabetçi", point: 0, condition: "" },
  { title: "Kazanmayı Seven", point: 0, condition: "" },
  { title: "Fark Yaratan", point: 0, condition: "" },
  { title: "Başarılarıyla Öne Çıkan", point: 0, condition: "" },
];
